[[Api.GetIpInfo]]
provider = "taobao"
url = "http://ip.taobao.com/service/getIpInfo.php?ip={}"
params = ["ip"]
format = "json"

[[Api.GetIpInfo]]
provider = "sina"
url = "http://int.dpool.sina.com.cn/iplookup/iplookup.php?format=json&ip={}"
params = ["ip"]
format = "json"

[[Api.GetIpInfo]]
provider = "pconline"
url = "http://whois.pconline.com.cn/ipJson.jsp?json=true&ip={}"
params = ["ip"]
format = "json"
